---
name: build_cpplibs
description: Builds CPP libraries.

inputs:
  build_type:
    description: Build type of the CPP libs (Release/Debug)
    required: true
    default: Release

  build_tests:
    description: Whether to build unit tests for CPP libs (ON/OFF)
    required: false
    default: OFF

runs:
  using: composite

  steps:
    - name: Install build tools
      run: just install_build_tools
      shell: bash

    - name: Build CPP libraries
      run: just build_project -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DBUILD_TESTS=${{ inputs.build_tests }}
      shell: bash
