---
repos:
  # Official pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: forbid-submodules
      - id: requirements-txt-fixer

  # Ensures C++/C files are formatted using clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        args:
          - -style=file:setuputils/.clang-format
        types_or: [c++, c]

  # Ensures Python files are formatted using autopep8 formatter
  - repo: https://github.com/hhatto/autopep8
    rev: v2.1.0
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --max-line-length=100]

  # Used for python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--explicit-package-bases, --python-executable, venv/bin/python]

  # Ensures python files are written using modern syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade

  # Ensures python imports are sorted according to (std, external, own) rule
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports

  # Ensures python files pass pylint checks
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [-rn, -sn]

  # Ensures yaml files are formatted
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']

  # Ensures json files are valid. Supports Json with Comments
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
