#ifndef MLCORE_INCLUDE_MLCORE_TENSORINITIALIZERS_ITENSORINITIALIZER_HPP
#define MLCORE_INCLUDE_MLCORE_TENSORINITIALIZERS_ITENSORINITIALIZER_HPP

namespace mlCore::tensorInitializers
{
/**
 * @brief Interface for classes used to initialize data for Tensors, ranges etc. The behaviour and returned values depend on the concrete implementation of the interface.
 * 
 * @tparam ValueType Type of the values generated by the initializer.
 */
template <typename ValueType>
class ITensorInitializer
{
public:
	/**
     * @brief Generates a value based on the concrete type of the initializer.
     * 
     * @return Generated value.
     */
	virtual ValueType yield() const = 0;

	/**
     * @brief Tells if the initializer is capable of generating a new value.
     * 
     * @return true If the initializer can return a new value. 
     * @return false In opposite case.
     */
	virtual bool canYield() const = 0;

	virtual ~ITensorInitializer() = default;
};
} // namespace mlCore::tensorInitializers

#endif